build:
  version: "3.0"
accounts:
  message: "Welcome to JoaoBank accounts related local APIs"
  contactDetails:
    name: "Joao Tinelli - Developer"
    email: "joaotinelli@joaobank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-4321
spring:
  datasource:
    url: "jdbc:mysql://accountsdb:3306/accountsdb"
    username: "root"
    password: "root"
