build:
  version: "3.0"
cards:
  message: "Welcome to JoaoBank cards related local APIs"
  contactDetails:
    name: "Joao Tinelli - Developer"
    email: "joaotinelli@alunos.utfpr.edu.br"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-4321
spring:
  datasource:
    url: "jdbc:mysql://cardsdb:3306/cardsdb"
    username: "root"
    password: "root"
